version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "02:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 16