name: This repo has x stars y forks

on:
  push:
    branches:
      - master
  fork:
  watch:
    types:
      - started
  schedule:
    - cron: 2 0 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: ouuan/This-repo-has-x-stars-y-forks-action@v2
        with:
          token: ${{secrets.STAR_FORK_TOKEN}}
          template: ":rainbow: This profile README has <starCount> stars & <forkCount> forks"