name: WakaTime Readme

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: alhul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{secrets.WAKATIME_API_KEY}}
